"""Tasks in sections

Revision ID: 302902cf5e3a
Revises: 93cd628e0815
Create Date: 2021-03-26 18:50:08.744943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302902cf5e3a'
down_revision = '93cd628e0815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_in_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_in_section')
    # ### end Alembic commands ###
