"""New structure of user stat

Revision ID: 3d3651941d35
Revises: 2a1b5c95e69a
Create Date: 2021-04-10 00:20:56.595710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d3651941d35'
down_revision = '2a1b5c95e69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stat', sa.Column('correct_attempts', sa.Integer(), nullable=True))
    op.add_column('user_stat', sa.Column('last_try_time', sa.DateTime(), nullable=True))
    op.add_column('user_stat', sa.Column('word_id', sa.Integer(), nullable=True))
    op.add_column('user_stat', sa.Column('wrong_attempts', sa.Integer(), nullable=True))
    op.drop_constraint('user_stat_ibfk_1', 'user_stat', type_='foreignkey')
    op.create_foreign_key(None, 'user_stat', 'word', ['word_id'], ['id'])
    op.drop_column('user_stat', 'result')
    op.drop_column('user_stat', 'task_id')
    op.drop_column('user_stat', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stat', sa.Column('time', mysql.DATETIME(), nullable=True))
    op.add_column('user_stat', sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user_stat', sa.Column('result', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_stat', type_='foreignkey')
    op.create_foreign_key('user_stat_ibfk_1', 'user_stat', 'task_in_section', ['task_id'], ['id'])
    op.drop_column('user_stat', 'wrong_attempts')
    op.drop_column('user_stat', 'word_id')
    op.drop_column('user_stat', 'last_try_time')
    op.drop_column('user_stat', 'correct_attempts')
    # ### end Alembic commands ###
