"""Collocation dictionary

Revision ID: 59114ccf6e42
Revises: 8b951341980e
Create Date: 2021-04-27 23:40:50.458398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59114ccf6e42'
down_revision = '8b951341980e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collocation_dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('collocation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collocation_id'], ['collocation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collocation_dictionary')
    # ### end Alembic commands ###
