"""Collocations

Revision ID: c4e547b2c78e
Revises: 3d3651941d35
Create Date: 2021-04-21 01:25:12.406677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e547b2c78e'
down_revision = '3d3651941d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_part', sa.String(length=64), nullable=True),
    sa.Column('second_part', sa.String(length=64), nullable=True),
    sa.Column('ru_translation', sa.String(length=64), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collocation')
    # ### end Alembic commands ###
